




#define strobeDurationMin_ID 0
#define strobeDurationMax_ID 1
#define strobeRadiusMin_ID 2
#define strobeRadiusMax_ID 3
#define strobeSpawnDistHori_ID 4
#define strobeSpawnDistVertMin_ID 5
#define strobeSpawnDistVertMax_ID 6
#define strobeMultiColor_ID 7
#define raveLaserEnabled_ID 8
#define raveLaserSpawnFreq_ID 9
#define raveLaserLength_ID 10
#define raveLaserSpawnDistHoriMin_ID 11
#define raveLaserSpawnDistHoriMax_ID 12
#define raveLaserSpawnDistVertMin_ID 13
#define raveLaserSpawnDistVertMax_ID 14
#define raveLaserBrightnessMin_ID 15
#define raveLaserBrightnessMax_ID 16
#define raveLaserDurationMin_ID 17
#define raveLaserDurationMax_ID 18
#define raveLaserThicknessMin_ID 19
#define raveLaserThicknessMax_ID 20
#define raveLaserNoiseMin_ID 21
#define raveLaserNoiseMax_ID 22
#define raveLaserFrameRateMin_ID 23
#define raveLaserFrameRateMax_ID 24
#define raveLaserMultiColor_ID 25
#define cameraPosFixedX_ID 26
#define cameraPosFixedY_ID 27
#define cameraPosFixedZ_ID 28
#define cameraPosOffX_ID 29
#define cameraPosOffY_ID 30
#define cameraPosOffZ_ID 31
#define cameraRotFixedX_ID 32
#define cameraRotFixedY_ID 33
#define cameraRotFixedZ_ID 34
#define cameraRotOffX_ID 35
#define cameraRotOffY_ID 36
#define cameraRotOffZ_ID 37
#define imAllFuckedUp_ID 38
#define thatWasntGrass_ID 39
#define thatWasntPunch_ID 40
#define fogNear_ID 41
#define fogFar_ID 42
#define myCameraSucks_ID 43
#define muteBulletHitSounds_ID 44
#define geigerChannel_ID 45
#define muteTempEntityGroundHitSound_ID 46
#define muteRicochetSound_ID 47
#define mutePlayerWeaponFire_ID 48
#define muteCrowbarSounds_ID 49
#define seeMonsterHealth_ID 50
#define event5011Allowed_ID 51
#define event5021Allowed_ID 52
#define event5031Allowed_ID 53
#define event5002Allowed_ID 54
#define event5004Allowed_ID 55
#define eventsAreFabulous_ID 56
#define glockOldReloadLogic_ID 57
#define testVar_ID 58
#define painArrowColorMode_ID 59
#define painFlashColorMode_ID 60
#define painFlashSuitless_ID 61
#define painFlashDrownMode_ID 62
#define firstPersonIdleDelayMin_ID 63
#define firstPersonIdleDelayMax_ID 64
#define forceDrawBatteryNumber_ID 65
#define canShowWeaponSelectAtDeath_ID 66
//#define endlessFlashlightBattery_ID 67
#define preE3UsesFailColors_ID 68
#define E3UsesFailColors_ID 69
#define preE3ShowsDamageIcons_ID 70
#define E3ShowsDamageIcons_ID 71
#define playerCrossbowMode_ID 72
#define tripmineAnimWaitsForFinish_ID 73
#define revolverLaserScope_ID 74
//#define python_zoomfov_ID 75
//#define crossbow_zoomfov_ID 76
//#define canApplyDefaultFOV_ID 77
#define auto_adjust_fov_ID 78
//#define auto_adjust_zoomfov_ID 79
#define cheat_infiniteclip_ID 80
#define cheat_infiniteammo_ID 81
#define cheat_minimumfiredelay_ID 82
#define cheat_minimumfiredelaycustom_ID 83
#define cheat_nogaussrecoil_ID 84
#define gaussRecoilSendsUpInSP_ID 85
#define raveEffectSpawnInterval_ID 86
#define fogTest_ID 87
//#define useAlphaCrosshair_ID 88
#define allowAlphaCrosshairWithoutGuns_ID 89
#define alphaCrosshairBlockedOnFrozen_ID 90
#define mirrorsReflectOnlyNPCs_ID 91
#define mirrorsDoNotReflectPlayer_ID 92
#define sv_germancensorship_ID 93
#define egonEffectsMode_ID 94
#define egonHitCloud_ID 95
//#define enableModPrintouts_ID 96
#define handGrenadePickupYieldsOne_ID 97
//#define skipTFDamageTextures_ID 98
//#define hud_moveselect_mousewheelsound_ID 99
#define timedDamageDeathRemoveMode_ID 100
//#define hud_moveselect_sound_ID 101
#define glockUseLastBulletAnim_ID 102
#define playerBarnacleVictimViewOffset_ID 103
#define trailTypeTest_ID 104
#define hornetTrail_ID 105
#define hornetTrailSolidColor_ID 106
#define hornetDeathModEasy_ID 107
#define hornetDeathModMedium_ID 108
#define hornetDeathModHard_ID 109
#define hornetZoomPuff_ID 110
#define hornetSpiral_ID 111
#define hornetSpeedMulti_ID 112
#define hornetSpeedDartMulti_ID 113
#define rocketTrailAlphaInterval_ID 114
#define rocketTrailAlphaScale_ID 115
#define rocketSkipIgnite_ID 116
#define gauss_mode_ID 117

#define painFlashDmgMin_ID 134
#define painFlashDmgExMult_ID 135
#define painFlashCumulativeMinDrowning_ID 136
#define painFlashCumulativeMax_ID 137
#define painFlashDrawOpacityMax_ID 138
#define painArrowDrawOpacityMin_ID 139
#define painArrowDrawOpacityMax_ID 140
#define painFlashFadeMult_ID 141
#define painArrowFadeMult_ID 142
#define painFlashArmorBlock_ID 143
#define painFlashDirTolerance_ID 144
#define painArrowCumulativeAppearMin_ID 145
#define painArrowCumulativeDmgJump_ID 146
#define painFlashPrintouts_ID 147
#define itemFlashCumulativeJump_ID 148
#define itemFlashDrawOpacityMin_ID 149
#define itemFlashDrawOpacityMax_ID 150
#define itemFlashFadeMult_ID 151
#define crossbowReloadSoundDelay_ID 152
#define crossbowFirePlaysReloadSound_ID 153
#define iHaveAscended_ID 154
#define drawViewModel_ID 155
#define drawHUD_ID 156
#define playerBulletHitEffectForceServer_ID 157
#define forceAllowServersideTextureSounds_ID 158
#define playerWeaponSpreadMode_ID 159
#define viewModelPrintouts_ID 160
#define viewModelSyncFixPrintouts_ID 161
#define textureHitSoundPrintouts_ID 162
//#define cl_holster_ID 163
#define playerWeaponTracerMode_ID 164
#define decalTracerExclusivity_ID 165
#define healthcolor_fullRedMin_ID 166
#define healthcolor_brightness_ID 167
#define healthcolor_yellowMark_ID 168
#define cl_drawExtraZeros_ID 169
#define hideDamage_ID 170
#define timedDamage_brightnessMax_ID 171
#define timedDamage_brightnessMin_ID 172
#define timedDamage_brightnessCap_ID 173
#define timedDamage_brightnessFloor_ID 174
#define timedDamage_flashSpeed_ID 175
#define timedDamage_debug_ID 176
#define myRocketsAreBarney_ID 177
#define wpn_glocksilencer_ID 178
#define sv_rpg_clipless_ID 179
#define egonRadiusDamageMode_ID 180
#define egonFireRateMode_ID 181


// Please.  Update this on changing the count above.
// Or bad things?     They will happen.
//  They.
//           WilL.
//                          haPpen.
//                                                          Thanks.
#define CVAR_CLIENTSENDOFF_COUNT 182







#define DEFAULT_gruntsCanHaveMP5Grenade 0
#define DEFAULT_hud_version 2
#define DEFAULT_hud_batterydraw 1
#define DEFAULT_strobeDurationMin 0.08
#define DEFAULT_strobeDurationMax 0.14
#define DEFAULT_strobeRadiusMin 280
#define DEFAULT_strobeRadiusMax 410
#define DEFAULT_strobeSpawnDistHori 180
#define DEFAULT_strobeSpawnDistVertMin 25
#define DEFAULT_strobeSpawnDistVertMax 75
#define DEFAULT_strobeMultiColor 1
#define DEFAULT_raveLaserEnabled 1
#define DEFAULT_raveLaserSpawnFreq 2.3
#define DEFAULT_raveLaserLength 1800
#define DEFAULT_raveLaserSpawnDistHoriMin 50
#define DEFAULT_raveLaserSpawnDistHoriMax 110
#define DEFAULT_raveLaserSpawnDistVertMin -5
#define DEFAULT_raveLaserSpawnDistVertMax 45
#define DEFAULT_raveLaserBrightnessMin 0.8
#define DEFAULT_raveLaserBrightnessMax 1.0
#define DEFAULT_raveLaserDurationMin 0.06
#define DEFAULT_raveLaserDurationMax 0.12
#define DEFAULT_raveLaserThicknessMin 0.8
#define DEFAULT_raveLaserThicknessMax 2.6
#define DEFAULT_raveLaserNoiseMin 0
#define DEFAULT_raveLaserNoiseMax 0
#define DEFAULT_raveLaserFrameRateMin 10
#define DEFAULT_raveLaserFrameRateMax 10
#define DEFAULT_raveLaserMultiColor 1
#define DEFAULT_cameraPosFixedX -1
#define DEFAULT_cameraPosFixedY -1
#define DEFAULT_cameraPosFixedZ -1
#define DEFAULT_cameraPosOffX 0
#define DEFAULT_cameraPosOffY 0
#define DEFAULT_cameraPosOffZ 260
#define DEFAULT_cameraRotFixedX 90
#define DEFAULT_cameraRotFixedY -1
#define DEFAULT_cameraRotFixedZ -1
#define DEFAULT_cameraRotOffX 0
#define DEFAULT_cameraRotOffY 0
#define DEFAULT_cameraRotOffZ 0
#define DEFAULT_imAllFuckedUp 0
#define DEFAULT_thatWasntGrass 0
#define DEFAULT_thatWasntPunch 0
#define DEFAULT_fogNear 380
#define DEFAULT_fogFar 1500
#define DEFAULT_NPCsTalkMore 0
#define DEFAULT_myCameraSucks 0
#define DEFAULT_shutupstuka 0
#define DEFAULT_chromeEffect 0
#define DEFAULT_hassaultSpinMovement 1
#define DEFAULT_hassaultIdleSpinSound 1
#define DEFAULT_hassaultFireSound 1
#define DEFAULT_muteBulletHitSounds 0
#define DEFAULT_mutePlayerPainSounds 0
#define DEFAULT_hassaultIdleSpinSoundChannel 6
#define DEFAULT_hassaultSpinUpDownSoundChannel 3
#define DEFAULT_hassaultFireSoundChannel 1
#define DEFAULT_geigerChannel 6
#define DEFAULT_hassaultWaitTime 4.0
#define DEFAULT_hassaultSpinupRemainTime 8.5
#define DEFAULT_hassaultResidualAttackTime 0.34
#define DEFAULT_hassaultSpinupStartTime 1.5
#define DEFAULT_hassaultVoicePitchMin 86
#define DEFAULT_hassaultVoicePitchMax 93
#define DEFAULT_hassaultFireSpread 0.060
#define DEFAULT_hassaultAllowGrenades 1
#define DEFAULT_muteTempEntityGroundHitSound 0
#define DEFAULT_houndeyeAttackMode 1
#define DEFAULT_muteRicochetSound 0
#define DEFAULT_mutePlayerWeaponFire 0
#define DEFAULT_muteCrowbarSounds 0
#define DEFAULT_scientistHealNPC 0
#define DEFAULT_scientistHealNPCDebug 0
#define DEFAULT_bulletholeAlertRange 300
#define DEFAULT_fleshhitmakessound 1
#define DEFAULT_nothingHurts 0
#define DEFAULT_seeMonsterHealth 0
#define DEFAULT_scientistHealNPCFract 0.8
#define DEFAULT_bullsquidRangeDisabled 0
#define DEFAULT_applyLKPPathFixToAll 0
#define DEFAULT_timedDamageAffectsMonsters 1
#define DEFAULT_scientistHealCooldown 44
#define DEFAULT_crazyMonsterPrintouts 0
#define DEFAULT_movementIsCompletePrintout 0
#define DEFAULT_bulletHoleAlertPrintout 0
#define DEFAULT_bulletholeAlertStukaOnly 1
#define DEFAULT_barneyPrintouts 0
#define DEFAULT_monsterSpawnPrintout 0
#define DEFAULT_zombieBulletResistance 1
#define DEFAULT_zombieBulletPushback 1
#define DEFAULT_houndeyePrintout 0
#define DEFAULT_quakeExplosionSound 2
#define DEFAULT_explosionDebrisSoundVolume 0.6
#define DEFAULT_noFlinchOnHard 1
#define DEFAULT_hassaultDrawLKP 0
#define DEFAULT_meleeDrawBloodModeA 9
#define DEFAULT_meleeDrawBloodModeB 9
#define DEFAULT_drawDebugBloodTrace 0
#define DEFAULT_meleeDrawBloodModeBFix 1
#define DEFAULT_meleeDrawBloodModeAOffset 5
#define DEFAULT_meleeDrawBloodModeBOffset 5
#define DEFAULT_wpn_glocksilencer 1
#define DEFAULT_panthereyeHasCloakingAbility 0
#define DEFAULT_hgruntSpeedMulti 1.0
#define DEFAULT_hgruntForceStrafeFireAnim 1
#define DEFAULT_hgruntLockRunAndGunTime 0.5
#define DEFAULT_hgruntHeadshotGore 1
#define DEFAULT_hgruntAllowStrafeFire 1
#define DEFAULT_thoroughHitBoxUpdates 1
#define DEFAULT_hgruntTinyClip 0
#define DEFAULT_hgruntStrafeAlwaysHasAmmo 0
#define DEFAULT_hgruntBrassEjectForwardOffset 18
#define DEFAULT_cl_muzzleflash 1
#define DEFAULT_agrunt_muzzleflash 1
#define DEFAULT_event5011Allowed 1
#define DEFAULT_event5021Allowed 1
#define DEFAULT_event5031Allowed 1
#define DEFAULT_event5002Allowed 1
#define DEFAULT_event5004Allowed 1
#define DEFAULT_eventsAreFabulous 0
#define DEFAULT_glockOldReloadLogic 0
#define DEFAULT_glockOldReloadLogicBarney 0
#define DEFAULT_barneyDroppedGlockAmmoCap 12
#define DEFAULT_drawCollisionBoundsAtDeath 0
#define DEFAULT_drawHitBoundsAtDeath 0
#define DEFAULT_islaveReviveFriendMode 0
#define DEFAULT_islaveReviveFriendChance 0.4
#define DEFAULT_islaveReviveFriendRange 230
#define DEFAULT_islaveReviveSelfMinDelay 14
#define DEFAULT_islaveReviveSelfMaxDelay 32
#define DEFAULT_islaveReviveSelfChance 0
#define DEFAULT_hgruntRunAndGunDistance 390
#define DEFAULT_hgruntPrintout 0
#define DEFAULT_testVar 0
#define DEFAULT_painArrowColorMode 1
#define DEFAULT_painFlashColorMode 2
#define DEFAULT_painFlashSuitless 0
#define DEFAULT_painFlashDrownMode 2
#define DEFAULT_firstPersonIdleDelayMin 5
#define DEFAULT_firstPersonIdleDelayMax 10
#define DEFAULT_forceDrawBatteryNumber 0
#define DEFAULT_offsetgivedistance 160
#define DEFAULT_offsetgivelookvertical 2
#define DEFAULT_canShowWeaponSelectAtDeath 1
#define DEFAULT_endlessFlashlightBattery 1
#define DEFAULT_preE3UsesFailColors 1
#define DEFAULT_E3UsesFailColors 1
#define DEFAULT_preE3ShowsDamageIcons 1
#define DEFAULT_E3ShowsDamageIcons 1
#define DEFAULT_playerCrossbowMode 1
#define DEFAULT_hassassinCrossbowMode 1
#define DEFAULT_tripmineAnimWaitsForFinish 1
#define DEFAULT_revolverLaserScope 1
//#define DEFAULT_python_zoomfov 0
//#define DEFAULT_crossbow_zoomfov 0
//#define DEFAULT_canApplyDefaultFOV 1
#define DEFAULT_auto_adjust_fov 1
//#define DEFAULT_auto_adjust_zoomfov 1
#define DEFAULT_cheat_infiniteclip 0
#define DEFAULT_cheat_infiniteammo 0
#define DEFAULT_cheat_minimumfiredelay 0
#define DEFAULT_cheat_minimumfiredelaycustom 0.048
#define DEFAULT_cheat_nogaussrecoil 0
#define DEFAULT_autoSneaky 0
#define DEFAULT_sv_longjump_chargemode 0
#define DEFAULT_cheat_touchNeverExplodes 0
#define DEFAULT_gaussRecoilSendsUpInSP 1
#define DEFAULT_drawDebugPathfinding 0
#define DEFAULT_STUcheckDistH 18
#define DEFAULT_STUcheckDistV 32
#define DEFAULT_STUcheckDistD 38
#define DEFAULT_STUextraTriangH 1.2
#define DEFAULT_STUextraTriangV 1.4
#define DEFAULT_STUrepelMulti 1.4
#define DEFAULT_STUSpeedMulti 1
#define DEFAULT_STUExplodeTest 0
#define DEFAULT_STUYawSpeedMulti 0.88
#define DEFAULT_STUDetection 1
#define DEFAULT_stukaAdvancedCombat 0
#define DEFAULT_drawDebugPathfinding2 0
#define DEFAULT_hassaultFriendlyFire 1
#define DEFAULT_myStrobe 0
#define DEFAULT_peopleStrobe 0
#define DEFAULT_forceWorldLightOff 0
#define DEFAULT_wildHeads 0
#define DEFAULT_raveEffectSpawnInterval 0.22
#define DEFAULT_drawBarnacleDebug 0
#define DEFAULT_fogTest 0
#define DEFAULT_sparksAllMulti 1
#define DEFAULT_sparksEnvMulti 0.5
#define DEFAULT_sparksButtonMulti 1
#define DEFAULT_sparksPlayerCrossbowMulti 1
#define DEFAULT_sparksComputerHitMulti 1
#define DEFAULT_sparksTurretDeathMulti 1
#define DEFAULT_sparksOspreyHitMulti 1
#define DEFAULT_sparksExplosionMulti 0.5
#define DEFAULT_sparksBeamMulti 1
#define DEFAULT_sparksAIFailMulti 1
#define DEFAULT_normalSpeedMulti 1
#define DEFAULT_noclipSpeedMulti 2.5
#define DEFAULT_jumpForceMulti 1
#define DEFAULT_apacheForceCinBounds 0
#define DEFAULT_apacheBottomBoundAdj 0
#define DEFAULT_apacheInfluence 0
#define DEFAULT_allowAlphaCrosshairWithoutGuns 0
#define DEFAULT_alphaCrosshairBlockedOnFrozen 1
#define DEFAULT_hgruntRunAndGunDotMin 0.91
#define DEFAULT_panthereyeJumpDotTol 1.2
#define DEFAULT_panthereyePrintout 0
#define DEFAULT_gargantuaPrintout 0
#define DEFAULT_squadmonsterPrintout 0
#define DEFAULT_hassaultPrintout 0
#define DEFAULT_barnaclePrintout 0
#define DEFAULT_friendlyPrintout 0
#define DEFAULT_stukaPrintout 0
#define DEFAULT_timedDamageEndlessOnHard 0
#define DEFAULT_mirrorsReflectOnlyNPCs 1
#define DEFAULT_mirrorsDoNotReflectPlayer 1
#define DEFAULT_r_shadows 0
#define DEFAULT_altSquadRulesRuntime 0
#define DEFAULT_hgruntLockStrafeTime 0.67
#define DEFAULT_pathfindIgnoreIsolatedNodes 1
#define DEFAULT_drawNodeAll 0
#define DEFAULT_drawNodeSpecial -1
#define DEFAULT_drawNodeConnections 0
#define DEFAULT_drawNodeAlternateTime 0
#define DEFAULT_nodeSearchStartVerticalOffset 30
#define DEFAULT_blockChangeLevelTrigger 0
#define DEFAULT_blockMusicTrigger 0
#define DEFAULT_blockMultiTrigger 0
#define DEFAULT_blockTeleportTrigger 0
#define DEFAULT_blockHurtTrigger 0
#define DEFAULT_blockAutosaveTrigger 0
#define DEFAULT_hideNodeGraphRebuildNotice 1
#define DEFAULT_barnacleTongueRetractDelay 2
#define DEFAULT_sv_germancensorship 0
#define DEFAULT_allowGermanModels 1
#define DEFAULT_germanRobotGibs 1
#define DEFAULT_germanRobotBleedsOil 1
#define DEFAULT_germanRobotDamageDecal 1
#define DEFAULT_germanRobotGibsDecal 1
#define DEFAULT_egonEffectsMode 3
#define DEFAULT_egonHitCloud 1
//#define DEFAULT_enableModPrintouts 0
#define DEFAULT_handGrenadePickupYieldsOne 1
#define DEFAULT_handGrenadesUseOldBounceSound 1
//#define DEFAULT_skipTFDamageTextures 1
#define DEFAULT_hud_moveselect_mousewheelsound 1
#define DEFAULT_timedDamageDeathRemoveMode 1
#define DEFAULT_hud_moveselect_sound 1
#define DEFAULT_barnacleCanGib 0
#define DEFAULT_sentryCanGib 0
#define DEFAULT_miniturretCanGib 0
#define DEFAULT_turretCanGib 0
#define DEFAULT_turretBleedsOil 0
#define DEFAULT_turretDamageDecal 0
#define DEFAULT_turretGibDecal 0
#define DEFAULT_canDropInSinglePlayer 0
#define DEFAULT_timedDamageIgnoresArmor 0
#define DEFAULT_itemBatteryPrerequisite 0
#define DEFAULT_playerExtraPainSoundsMode 2
#define DEFAULT_timedDamageDisableViewPunch 0
#define DEFAULT_batteryDrainsAtDeath 1
#define DEFAULT_batteryDrainsAtAdrenalineMode 1
#define DEFAULT_canTakeLongJump 2
#define DEFAULT_printOutCommonTimables 0
#define DEFAULT_playerBrightLight 0
#define DEFAULT_disablePainPunchAutomatic 1
#define DEFAULT_gargantuaCorpseDeath 1
#define DEFAULT_gargantuaFallSound 1
#define DEFAULT_gargantuaBleeds 1
#define DEFAULT_shrapMode 1
#define DEFAULT_shrapRand 190
#define DEFAULT_shrapRandHeightExtra 140
#define DEFAULT_explosionShrapnelMulti 1
#define DEFAULT_useAlphaSparks 1
#define DEFAULT_emergencyFix 0
#define DEFAULT_timedDamageReviveRemoveMode 1
//#define DEFAULT_forceAllowMonsterSpawning 0
#define DEFAULT_ospreyIgnoresGruntCount 0
#define DEFAULT_mp5GrenadeInheritsPlayerVelocity 0.11
#define DEFAULT_crossbowInheritsPlayerVelocity 0.06
#define DEFAULT_fastHornetsInheritsPlayerVelocity 0.03
#define DEFAULT_snarkInheritsPlayerVelocity 0.17
#define DEFAULT_chumtoadInheritsPlayerVelocity 0.15
#define DEFAULT_weaponPickupPlaysAnyReloadSounds 1
#define DEFAULT_glockUseLastBulletAnim 1
#define DEFAULT_playerBarnacleVictimViewOffset -6
#define DEFAULT_hgruntMovementDeltaCheck 1
#define DEFAULT_hiddenMemPrintout 0
#define DEFAULT_hassaultExtraMuzzleFlashRadius 0.85
#define DEFAULT_hassaultExtraMuzzleFlashBrightness 0.78
#define DEFAULT_hassaultExtraMuzzleFlashForward 4.6
#define DEFAULT_leaderlessSquadAllowed 1
#define DEFAULT_nodeConnectionBreakableCheck 1
#define DEFAULT_playerReviveInvincibilityTime 1.6
#define DEFAULT_playerReviveBuddhaMode 1
#define DEFAULT_playerReviveTimeBlocksTimedDamage 1
#define DEFAULT_hassaultBulletDamageMulti 1.6
#define DEFAULT_hassaultBulletsPerShot 2
#define DEFAULT_hassaultFireAnimSpeedMulti 2.4
#define DEFAULT_hassaultMeleeAnimSpeedMulti 1.36
#define DEFAULT_hassassinCrossbowReloadSoundDelay 1.1
#define DEFAULT_hgruntStrafeAnimSpeedMulti 1.25
#define DEFAULT_hgruntRunAndGunAnimSpeedMulti 1.14
#define DEFAULT_cheat_iwantguts 0
#define DEFAULT_nodeDetailPrintout 0
#define DEFAULT_soundAttenuationStuka 0.85
#define DEFAULT_soundVolumeStuka 1
#define DEFAULT_cineChangelevelFix 3
#define DEFAULT_drawDebugCine 0
#define DEFAULT_cineAllowSequenceOverwrite 0
#define DEFAULT_stukaInflictsBleeding 0
#define DEFAULT_animationKilledBoundsRemoval 1
#define DEFAULT_gargantuaKilledBoundsAssist 1
#define DEFAULT_bullsquidSpitTrajTimeMin 1.0
#define DEFAULT_bullsquidSpitTrajTimeMax 1.5
#define DEFAULT_bullsquidSpitTrajDistMin 900
#define DEFAULT_bullsquidSpitTrajDistMax 1400
#define DEFAULT_bullsquidSpitGravityMulti 1
#define DEFAULT_cl_bullsquidspit 0
#define DEFAULT_cl_bullsquidspitarc 0
#define DEFAULT_bullsquidSpitUseAlphaModel 0
#define DEFAULT_bullsquidSpitUseAlphaEffect 0
#define DEFAULT_bullsquidSpitEffectSpread 0.37
#define DEFAULT_bullsquidSpitEffectMin 90
#define DEFAULT_bullsquidSpitEffectMax 120
#define DEFAULT_bullsquidSpitEffectHitMin 60
#define DEFAULT_bullsquidSpitEffectHitMax 80
#define DEFAULT_bullsquidSpitEffectSpawn 4
#define DEFAULT_bullsquidSpitEffectHitSpawn 4
#define DEFAULT_bullsquidSpitSpriteScale 0.5
#define DEFAULT_bullsquidSpitAlphaScale 0.8
#define DEFAULT_scientistBravery 1
#define DEFAULT_barneyUnholsterTime 18
#define DEFAULT_barneyUnholsterAnimChoice 1
#define DEFAULT_trailTypeTest -1
#define DEFAULT_hornetTrail 0
#define DEFAULT_hornetTrailSolidColor 1
#define DEFAULT_hornetDeathModEasy 2
#define DEFAULT_hornetDeathModMedium 2
#define DEFAULT_hornetDeathModHard 0
#define DEFAULT_hornetZoomPuff 0
#define DEFAULT_hornetSpiral 0
#define DEFAULT_hornetSpeedMulti 1
#define DEFAULT_hornetSpeedDartMulti 2
#define DEFAULT_cl_rockettrail 0
#define DEFAULT_rocketTrailAlphaInterval 0.035
#define DEFAULT_rocketTrailAlphaScale 0.21
#define DEFAULT_rocketSkipIgnite 1
#define DEFAULT_agruntHornetRandomness 0.1
#define DEFAULT_hornetSpiralPeriod 0.11
#define DEFAULT_hornetSpiralAmplitude 59
#define DEFAULT_cl_hornetspiral 0
#define DEFAULT_cl_hornettrail 0
#define DEFAULT_hud_drawammobar 0
#define DEFAULT_hud_weaponselecthideslower 1
#define DEFAULT_hud_drawsidebarmode 0
#define DEFAULT_gauss_mode 1
#define DEFAULT_gauss_primaryonly 0
#define DEFAULT_gauss_reflectdealsdamage 1
#define DEFAULT_gauss_chargeanimdelay 0
#define DEFAULT_gauss_chargeworkdelay 0
#define DEFAULT_gauss_secondarychargetimereq 0.5
#define DEFAULT_gauss_primaryreflects 1
#define DEFAULT_gauss_primarypierces 1
#define DEFAULT_gauss_secondaryreflects 1
#define DEFAULT_gauss_secondarypierces 1
#define DEFAULT_gauss_primarypunchthrough 0
#define DEFAULT_gauss_secondarypunchthrough 1
#define DEFAULT_gauss_betweenattackdelay 0.2
#define DEFAULT_gauss_secondarychargemindelay 0.5
#define DEFAULT_gauss_chargeMaxAmmo_SP 13
#define DEFAULT_gauss_chargeMaxAmmo_MP 10
#define DEFAULT_gauss_chargeInterval_SP 0.3
#define DEFAULT_gauss_chargeInterval_MP 0.1
#define DEFAULT_painFlashDmgMin 0.3
#define DEFAULT_painFlashDmgExMult 0.08
#define DEFAULT_painFlashCumulativeMinDrowning 0.5
#define DEFAULT_painFlashCumulativeMax 1.4
#define DEFAULT_painFlashDrawOpacityMax 0.8
#define DEFAULT_painArrowDrawOpacityMin 0.5
#define DEFAULT_painArrowDrawOpacityMax 1.0
#define DEFAULT_painFlashFadeMult 1.7
#define DEFAULT_painArrowFadeMult 1.5
#define DEFAULT_painFlashArmorBlock 0.5
#define DEFAULT_painFlashDirTolerance 0.8
#define DEFAULT_painArrowCumulativeAppearMin 0.4
#define DEFAULT_painArrowCumulativeDmgJump 1.2
#define DEFAULT_painFlashPrintouts 0
#define DEFAULT_itemFlashCumulativeJump 1.15
#define DEFAULT_itemFlashDrawOpacityMin 0.0
#define DEFAULT_itemFlashDrawOpacityMax 0.75
#define DEFAULT_itemFlashFadeMult 1.5
#define DEFAULT_chumtoadPrintout 0
#define DEFAULT_crossbowReloadSoundDelay -1
#define DEFAULT_crossbowFirePlaysReloadSound 0
#define DEFAULT_pathfindFidgetFailTime 0.2
#define DEFAULT_pathfindPrintout 0
#define DEFAULT_pathfindTopRampFixDistance 100
#define DEFAULT_pathfindTopRampFixDraw 0
#define DEFAULT_iHaveAscended 0
#define DEFAULT_pathfindLooseMapNodes 0
#define DEFAULT_pathfindRampFix 0
#define DEFAULT_chumtoadPlayDeadFoolChance 0.5
#define DEFAULT_animationFramerateMulti 1
#define DEFAULT_pathfindNodeToleranceMulti 1
#define DEFAULT_friendlyPianoFollowVolume 0.7
#define DEFAULT_friendlyPianoOtherVolume 1.0
#define DEFAULT_showtriggers 0
#define DEFAULT_tentacleAlertSound 1
#define DEFAULT_tentacleSwingSound1 0
#define DEFAULT_tentacleSwingSound2 0
#define DEFAULT_playerFollowerMax 1
#define DEFAULT_announcerIsAJerk 0
#define DEFAULT_playerUseDrawDebug 0
#define DEFAULT_playerChumtoadThrowDrawDebug 0
#define DEFAULT_peaceOut 0
#define DEFAULT_drawViewModel 1
#define DEFAULT_drawHUD 1
#define DEFAULT_disablePauseSinglePlayer 0
#define DEFAULT_playerBulletHitEffectForceServer 0
#define DEFAULT_forceAllowServersideTextureSounds 0
#define DEFAULT_playerWeaponSpreadMode 0
#define DEFAULT_monsterAIForceFindDistance 0
#define DEFAULT_baseEntityDamagePushNormalMulti 0
#define DEFAULT_baseEntityDamagePushVerticalBoost 0
#define DEFAULT_baseEntityDamagePushVerticalMulti 0
#define DEFAULT_baseEntityDamagePushVerticalMinimum 0
#define DEFAULT_viewModelPrintouts 0
#define DEFAULT_viewModelSyncFixPrintouts 0
#define DEFAULT_textureHitSoundPrintouts 0
#define DEFAULT_hgruntAllowGrenades 1
#define DEFAULT_scheduleInterruptPrintouts 0
#define DEFAULT_animationPrintouts 0
#define DEFAULT_hassaultMeleeAttackEnabled 1
#define DEFAULT_pathfindStumpedWaitTime 6
#define DEFAULT_pathfindStumpedMode 2
#define DEFAULT_pathfindStumpedForgetEnemy 0
#define DEFAULT_pathfindEdgeCheck 1
#define DEFAULT_RadiusDamageDrawDebug 0
#define DEFAULT_AlienRadiationImmunity 0
#define DEFAULT_customLogoSprayMode 0
#define DEFAULT_monsterFadeOutRate 120
#define DEFAULT_playerFadeOutRate 100
#define DEFAULT_drawDebugEnemyLKP 0
#define DEFAULT_trackchangePrintouts 0
#define DEFAULT_trackTrainPrintouts 0
#define DEFAULT_cl_holster 0
#define DEFAULT_playerWeaponTracerMode 5
#define DEFAULT_monsterWeaponTracerMode 2
#define DEFAULT_decalTracerExclusivity 0
#define DEFAULT_monsterToPlayerHitgroupSpecial 0
#define DEFAULT_multiplayerCrowbarHitSoundMode 1
#define DEFAULT_healthcolor_fullRedMin 15
#define DEFAULT_healthcolor_brightness 125
#define DEFAULT_healthcolor_yellowMark 70
#define DEFAULT_cl_drawExtraZeros 0
#define DEFAULT_pathfindLargeBoundFix 1
#define DEFAULT_flyerKilledFallingLoop 1
#define DEFAULT_floaterDummy 0
#define DEFAULT_barneyDummy 0
#define DEFAULT_ladderCycleMulti 1
#define DEFAULT_ladderSpeedMulti 1
#define DEFAULT_barnacleGrabNoInterpolation 0
#define DEFAULT_hideDamage 0
#define DEFAULT_timedDamage_brightnessMax 256
#define DEFAULT_timedDamage_brightnessMin 0
#define DEFAULT_timedDamage_brightnessCap -1
#define DEFAULT_timedDamage_brightnessFloor -1
#define DEFAULT_timedDamage_flashSpeed 2
#define DEFAULT_timedDamage_debug 0
#define DEFAULT_wallHealthDoor_closeDelay 0.75
#define DEFAULT_houndeye_attack_canGib 0
#define DEFAULT_myRocketsAreBarney 0
#define DEFAULT_hassassinCrossbowDebug 0
#define DEFAULT_crossbowBoltDirectionAffectedByWater 0
#define DEFAULT_kingpinDebug 0
#define DEFAULT_minimumRespawnDelay 2
#define DEFAULT_r_glowshell_debug 0
#define DEFAULT_cl_viewpunch 1
#define DEFAULT_cl_explosion 0
#define DEFAULT_soundSentenceSave 1
#define DEFAULT_pissedNPCs 0

#define DEFAULT_hud_logo 0
#define DEFAULT_hud_brokentrans 0
#define DEFAULT_cl_fvox 1
#define DEFAULT_cl_ladder 1
#define DEFAULT_precacheAll 1
#define DEFAULT_cl_interp_entity 1

#define DEFAULT_hud_swapFirstTwoBuckets 0
#define DEFAULT_ignoreMultiplayerSkillOverride 1

#define DEFAULT_m_rawinput 0
#define DEFAULT_cl_earlyaccess 0
#define DEFAULT_cl_viewroll 1
#define DEFAULT_drawDebugCrowbar 0

#define DEFAULT_blastExtraArmorDamageMode 0
#define DEFAULT_hud_batteryhiddendead 1
#define DEFAULT_hyperBarney 0
#define DEFAULT_monsterKilledToss 2
#define DEFAULT_interpolation_movetypestep_mindelta 0.06
#define DEFAULT_sv_bloodparticlemode 1
#define DEFAULT_cl_interp_view_extra 1
#define DEFAULT_cl_interp_view_standard 1
#define DEFAULT_cl_interp_viewmodel 1
#define DEFAULT_sv_explosionknockback 1
#define DEFAULT_cl_gaussfollowattachment 1
#define DEFAULT_cl_mp5_viewpunch_mod 0
#define DEFAULT_cl_breakholster 0
#define DEFAULT_pausecorrection1 1
#define DEFAULT_pausecorrection2 2
#define DEFAULT_hud_rpg_clipless 1
#define DEFAULT_sv_rpg_clipless 1
#define DEFAULT_cl_viewmodel_fidget 2
#define DEFAULT_sv_player_midair_fix 0
#define DEFAULT_sv_player_midair_accel 0
#define DEFAULT_pathfindIgnoreNearestNodeCache 0
#define DEFAULT_pathfindIgnoreStaticRoutes 0
#define DEFAULT_pathfindForcePointHull 0
#define DEFAULT_pathfindNearestNodeExtra 0
#define DEFAULT_sv_turret_postdeath 0
#define DEFAULT_cl_mp5_evil_skip 0
#define DEFAULT_egonRadiusDamageMode 0
#define DEFAULT_egonFireRateMode 0
#define DEFAULT_sv_explosion_shake 0
#define DEFAULT_sv_explosion_shake_range 1
#define DEFAULT_sv_explosion_shake_amp 1
#define DEFAULT_sv_explosion_shake_freq 1
#define DEFAULT_sv_explosion_shake_duration 1
#define DEFAULT_sv_gargantua_throwattack 1
#define DEFAULT_cl_viewpunch_mod 1
#define DEFAULT_cl_gauss_viewpunch_mod 1
#define DEFAULT_pathfindMonsterclipFreshLogic 2
#define DEFAULT_sv_rpg_projectile_model 1
#define DEFAULT_hmilitaryDeadInvestigate 1
#define DEFAULT_playerDeadTruce 0
#define DEFAULT_playerDeadTalkerBehavior 1


