version: 1.0.{build}

branches:
  only:
    - master

environment:
  matrix:
    - os: Visual Studio 2013
      GENERATOR_NAME: "Visual Studio 12 2013"
    - os: Visual Studio 2015
      GENERATOR_NAME: "Visual Studio 14 2015"
# TODO: Uncomment when AppVeyor will provide XP toolchain for VS2017
#    - os: Visual Studio 2017
#      GENERATOR_NAME: "Visual Studio 15 2017"

clone_folder: c:\projects\xash\hlsdk-xash3d

build:
  project: INSTALL.vcxproj
  verbosity: normal

configuration:
  - Debug

before_build:
  - git submodule update --init --recursive
  - cmake -G "%GENERATOR_NAME%"
