Schedule
	SCHED_HUMAN_TAKE_COVER
	Tasks
		TASK_STOP_MOVING               0
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_HUMAN_TAKECOVER_FAILED
		TASK_WAIT                      0.2
		TASK_FIND_COVER_FROM_ENEMY     0
		TASK_HUMAN_SOUND_COVER         0.5
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_REMEMBER                  MEMORY:INCOVER
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_HUMAN_WAIT_IN_COVER
	Interrupts
		COND_HEAR_DANGER
		COND_ENEMY_DEAD

Schedule
	SCHED_HUMAN_RETREAT
	Tasks
		TASK_STOP_MOVING               0
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_HUMAN_TAKECOVER_FAILED
		TASK_FIND_COVER_FROM_ENEMY     0
		TASK_HUMAN_SOUND_RETREATING    0
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_REMEMBER                  MEMORY:INCOVER
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_HUMAN_WAIT_IN_COVER
	Interrupts
		COND_HEAR_DANGER
		COND_ENEMY_DEAD

Schedule
	SCHED_HUMAN_GRENADE_COVER
	Tasks
		TASK_STOP_MOVING               0
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_HUMAN_TAKE_COVER
		TASK_FIND_FAR_NODE_COVER_FROM_ENEMY 384
		TASK_HUMAN_PLAY_SEQUENCE_WAIT  ACTIVITY:ACT_SPECIAL_ATTACK1
//		TASK_CLEAR_MOVE_WAIT           0
		TASK_HUMAN_SOUND_COVER         0
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_HUMAN_WAIT_IN_COVER
	Interrupts
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_TOSS_GRENADE_COVER
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_FACE_TOSS_DIR       0
		TASK_HUMAN_SOUND_THROW         0.5
		TASK_RANGE_ATTACK2             0
		TASK_HUMAN_DEFER_SQUAD_GRENADES 0
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_HUMAN_TAKE_COVER
	Interrupts
		COND_HEAR_DANGER

// Run towards cover, but stop running if we don't hear danger anymore
Schedule
	SCHED_HUMAN_TAKE_COVER_FROM_BEST_SOUND
	Tasks
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_FLEE_FROM_BEST_SOUND
		TASK_STOP_MOVING               0
		TASK_SET_TOLERANCE_DISTANCE    24
		TASK_STORE_BESTSOUND_REACTORIGIN_IN_SAVEPOSITION 0
		TASK_FIND_COVER_FROM_BEST_SOUND 0
		TASK_HUMAN_CROUCH              0
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_REMEMBER                  MEMORY:INCOVER
		TASK_FACE_SAVEPOSITION         0
	Interrupts
		COND_NO_HEAR_DANGER

Schedule
	SCHED_HUMAN_COWER
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_CROUCH              0
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_COWER
	Interrupts

Schedule
	SCHED_HUMAN_HEAR_SOUND
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_CROUCH              0
		TASK_HUMAN_SOUND_HEAR          0.5
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_FACE_IDEAL                0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE // stop possible turn animation
		TASK_WAIT                      3
	Interrupts
		COND_NEW_ENEMY
		COND_SEE_FEAR
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_PROVOKED
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_INVESTIGATE_SOUND
	Tasks
		TASK_STOP_MOVING               0
		TASK_STORE_LASTPOSITION        0
		TASK_GET_PATH_TO_BESTSOUND     0
		TASK_HUMAN_CROUCH              0
		TASK_HUMAN_SOUND_HEAR          0.5
		TASK_FACE_IDEAL                0
		TASK_WALK_PATH                 0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE_ANGRY
		TASK_WAIT                      10
		TASK_GET_PATH_TO_LASTPOSITION  0
		TASK_WALK_PATH                 0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_CLEAR_LASTPOSITION        0
	Interrupts
		COND_NEW_ENEMY
		COND_SEE_FEAR
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_VICTORY_DANCE
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_UNCROUCH            0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_HUMAN_SOUND_VICTORY       0
		TASK_WAIT                      4
		TASK_SUGGEST_STATE             STATE:IDLE
	Interrupts
		COND_NEW_ENEMY
		COND_SEE_FEAR
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_PROVOKED

Schedule
	SCHED_HUMAN_HIDE_RELOAD
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_CROUCH              0
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_RELOAD
		TASK_FIND_COVER_FROM_ENEMY     0
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_REMEMBER                  MEMORY:INCOVER
		TASK_FACE_ENEMY                0
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_RELOAD
	Interrupts
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_ENEMY_DEAD

Schedule
	SCHED_HUMAN_RELOAD
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_CROUCH              0
		TASK_RELOAD                    0
	Interrupts
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_FIND_MEDIC_COMBAT
	Tasks
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_TAKE_COVER_FROM_ENEMY
		TASK_STOP_MOVING               0
		TASK_HUMAN_SOUND_HELP          0.0
		TASK_HUMAN_FIND_MEDIC          0
		TASK_GET_PATH_TO_TARGET        0
		TASK_MOVE_TO_TARGET_RANGE      50
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_FACE_TARGET               179
		TASK_HUMAN_UNCROUCH            0
		TASK_WAIT                      2.0
	Interrupts
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_FIND_MEDIC
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_SOUND_MEDIC         0.0
		TASK_HUMAN_FIND_MEDIC          0
		TASK_GET_PATH_TO_TARGET        0
		TASK_MOVE_TO_TARGET_RANGE      50 //		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_FACE_TARGET               179
		TASK_HUMAN_UNCROUCH            0
		TASK_WAIT                      2.0
	Interrupts
		COND_NEW_ENEMY
		COND_SEE_FEAR
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_PROVOKED

Schedule
	SCHED_HUMAN_SIGNAL_ATTACK
	Tasks
		TASK_STOP_MOVING               0
		TASK_FACE_IDEAL                0
		TASK_HUMAN_SOUND_ATTACK        0
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_RANGE_ATTACK1
	Interrupts
		COND_ENEMY_DEAD
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_NO_PRIMARY_AMMO
		COND_WEAPON_BLOCKED_BY_FRIEND
		COND_WEAPON_SIGHT_OCCLUDED

Schedule
	SCHED_HUMAN_SIGNAL_SURPRESS
	Tasks
		TASK_STOP_MOVING               0
		TASK_FACE_IDEAL                0
		TASK_HUMAN_SOUND_SURPRESS      0
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_HUMAN_SURPRESS
	Interrupts
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_SIGNAL_SEARCH_AND_DESTROY
	Tasks
		TASK_STOP_MOVING               0
		TASK_FACE_IDEAL                0
		TASK_HUMAN_SOUND_SEARCH_AND_DESTROY 0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE_ANGRY
		TASK_WAIT                      2
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_HUMAN_SEARCH_AND_DESTROY
	Interrupts
		COND_HEAR_DANGER
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE

Schedule
	SCHED_HUMAN_SIGNAL_RETREAT
	Tasks
		TASK_STOP_MOVING               0
		TASK_FACE_IDEAL                0
		TASK_HUMAN_SOUND_RETREAT       0
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_TAKE_COVER_FROM_ENEMY
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_HUMAN_TAKECOVER_FAILED
		TASK_WAIT                      0.2
		TASK_FIND_COVER_FROM_ENEMY     0
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_REMEMBER                  MEMORY:INCOVER
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_HUMAN_WAIT_IN_COVER
	Interrupts
		COND_HEAR_DANGER
		COND_NEW_ENEMY
		COND_ENEMY_DEAD
		COND_NO_PRIMARY_AMMO
		COND_PROVOKED

Schedule
	SCHED_HUMAN_SIGNAL_COME_TO_ME
	Tasks
		TASK_STOP_MOVING               0
		TASK_FACE_IDEAL                0
		TASK_HUMAN_UNCROUCH            0
		TASK_HUMAN_SOUND_COME_TO_ME    0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_WAIT                      10
	Interrupts
		COND_HEAR_DANGER
		COND_NEW_ENEMY
		COND_SEE_FEAR
		COND_SEE_DISLIKE
		COND_SEE_HATE
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_PROVOKED

Schedule
	SCHED_HUMAN_SIGNAL_CHECK_IN
	Tasks
		TASK_STOP_MOVING               0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_HUMAN_SOUND_CHECK_IN      0
		TASK_WAIT                      5
	Interrupts
		COND_HEAR_DANGER
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_PROVOKED

Schedule
	SCHED_HUMAN_CHECK_IN
	Tasks
		TASK_STOP_MOVING               0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_HUMAN_SOUND_CLEAR         0
		TASK_WAIT                      1
	Interrupts
		COND_HEAR_DANGER
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_PROVOKED

Schedule
	SCHED_HUMAN_FOUND_ENEMY
	Tasks
		TASK_STOP_MOVING               0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_SOUND_FOUND_ENEMY   0
	Interrupts
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_RANGE_ATTACK1
	Tasks
		TASK_STOP_MOVING               0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_SOUND_CHARGE        0.1
		TASK_RANGE_ATTACK1             0
	Interrupts
		COND_NEW_ENEMY
		COND_ENEMY_DEAD
		COND_HEAVY_DAMAGE
		COND_ENEMY_OCCLUDED
		COND_HEAR_DANGER
		COND_NO_PRIMARY_AMMO
		COND_WEAPON_BLOCKED_BY_FRIEND
		COND_WEAPON_SIGHT_OCCLUDED

Schedule
	SCHED_HUMAN_RANGE_ATTACK2
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_FACE_TOSS_DIR       0
		TASK_HUMAN_SOUND_THROW         0.5
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_RANGE_ATTACK2
		TASK_HUMAN_DEFER_SQUAD_GRENADES 0
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_HUMAN_WAIT_IN_COVER
	Interrupts
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_ESTABLISH_LINE_OF_FIRE
	Tasks
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_ESTABLISH_LINE_OF_FIRE_FALLBACK
		TASK_GET_PATH_TO_ENEMY_LOS     0
		TASK_HUMAN_SOUND_CHARGE        0.7
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_COMBAT_FACE
	Interrupts
		COND_NEW_ENEMY
		COND_ENEMY_DEAD
		COND_LOST_ENEMY
		COND_CAN_RANGE_ATTACK1
		COND_CAN_MELEE_ATTACK1
		COND_CAN_RANGE_ATTACK2
		COND_CAN_MELEE_ATTACK2
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_STRAFE
	Tasks
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_RANGE_ATTACK1
		TASK_GET_STRAFE_PATH           0
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_COMBAT_FACE
	Interrupts
		COND_NEW_ENEMY
		COND_ENEMY_DEAD
		COND_LOST_ENEMY
//		COND_CAN_RANGE_ATTACK1
		COND_CAN_MELEE_ATTACK1
//		COND_CAN_RANGE_ATTACK2
		COND_CAN_MELEE_ATTACK2
		COND_HEAR_DANGER

// M79 user calls this instead of SCHED_BACK_AWAY_FROM_ENEMY when too close.
// We stop running when we are about twice this weapon's min range from the
// target so we can stop, turn, and shoot before the enemy catches up.
Schedule
	SCHED_HUMAN_MOVE_TO_WEAPON_RANGE
	Tasks
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_TAKE_COVER_FROM_ENEMY
//		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_BACK_AWAY_FROM_ENEMY
//		TASK_STORE_ENEMY_POSITION_IN_SAVEPOSITION 0
//		TASK_FIND_BACKAWAY_FROM_SAVEPOSITION      0
		TASK_GET_PATH_TO_ENEMY_LOS     0
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
	Interrupts
//		COND_NEW_ENEMY
		COND_ENEMY_DEAD
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_EXPLOSIVE_ELOF
	Tasks
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_HUMAN_MELEE_ELOF
		TASK_HUMAN_GET_EXPLOSIVE_PATH_TO_ENEMY 0
		TASK_HUMAN_SOUND_CHARGE        0.7
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
	Interrupts
		COND_NEW_ENEMY
		COND_ENEMY_DEAD
		COND_CAN_RANGE_ATTACK1
		COND_CAN_MELEE_ATTACK1
		COND_CAN_RANGE_ATTACK2
		COND_CAN_MELEE_ATTACK2
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_MELEE_ELOF
	Tasks
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_TAKE_COVER_FROM_ENEMY
		TASK_HUMAN_GET_MELEE_PATH_TO_ENEMY 0
		TASK_HUMAN_SOUND_CHARGE        0.7
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
	Interrupts
		COND_NEW_ENEMY
		COND_ENEMY_DEAD
		COND_CAN_RANGE_ATTACK1
		COND_CAN_MELEE_ATTACK1
		COND_CAN_RANGE_ATTACK2
		COND_CAN_MELEE_ATTACK2
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_STANDOFF
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_CROUCH              0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_HUMAN_SOUND_TAUNT         0.2
		TASK_WAIT_FACE_ENEMY           3
	Interrupts
		COND_CAN_MELEE_ATTACK1
		COND_CAN_MELEE_ATTACK2
		COND_CAN_RANGE_ATTACK1
		COND_CAN_RANGE_ATTACK2
		COND_ENEMY_DEAD
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_PLAYER
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_UNCROUCH
	Tasks
		TASK_HUMAN_UNCROUCH            0
//		TASK_SOUND_IDLE                0
//		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
//		TASK_WAIT                      3
	Interrupts
		COND_PROVOKED
		COND_NEW_ENEMY
		COND_SEE_FEAR
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_UNCROUCH_SCRIPT
	Tasks
		TASK_HUMAN_UNCROUCH            0
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_AISCRIPT
	Interrupts

Schedule
	SCHED_HUMAN_WAIT_IN_COVER
	Tasks
		TASK_STOP_MOVING               0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_WAIT_FACE_ENEMY           1
	Interrupts
		COND_NEW_ENEMY
		COND_SEE_ENEMY
		COND_HEAR_DANGER
		COND_CAN_RANGE_ATTACK1
		COND_CAN_RANGE_ATTACK2
		COND_CAN_MELEE_ATTACK1
		COND_CAN_MELEE_ATTACK2

// This is NOT for following the player, only moving to help a squadmate
Schedule
	SCHED_HUMAN_FOLLOW
	Tasks
	    TASK_STOP_MOVING               0
	    TASK_GET_PATH_TO_TARGET        0
		TASK_MOVE_TO_TARGET_RANGE      128
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_TARGET_FACE
	Interrupts
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_PROVOKED

Schedule
	SCHED_HUMAN_FOLLOW_CLOSE
	Tasks
		TASK_MOVE_TO_TARGET_RANGE      64
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_TARGET_FACE
	Interrupts
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_PROVOKED

Schedule
	SCHED_HUMAN_TURN_ROUND
	Tasks
		TASK_STOP_MOVING               0
		TASK_TURN_LEFT                 179
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE_ANGRY
		TASK_WAIT                      1
	Interrupts
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_PROVOKED
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_SURPRESS
	Tasks
		TASK_STOP_MOVING               0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_HUMAN_SOUND_SURPRESSING   0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
	Interrupts
		COND_NEW_ENEMY
		COND_ENEMY_DEAD
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_NO_PRIMARY_AMMO
		COND_WEAPON_BLOCKED_BY_FRIEND
		COND_PROVOKED

Schedule
	SCHED_HUMAN_MOVE_TO_ENEMY_LKP
	Tasks
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_HUMAN_SURPRESS
//		TASK_GET_PATH_TO_ENEMY_LKP     0
		TASK_GET_PATH_TO_ENEMY_LKP_LOS 0
		TASK_RUN_PATH                  0
//		TASK_HUMAN_WAIT_GOAL_VISIBLE   0
		TASK_STOP_MOVING               0
	Interrupts
		COND_NEW_ENEMY
		COND_CAN_RANGE_ATTACK1
		COND_CAN_MELEE_ATTACK1
		COND_CAN_RANGE_ATTACK2
		COND_CAN_MELEE_ATTACK2
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_SEARCH_AND_DESTROY
	Tasks
		TASK_STOP_MOVING               0
		TASK_STORE_LASTPOSITION        0
		TASK_FIND_FAR_NODE_COVER_FROM_ORIGIN 512
		TASK_FACE_IDEAL                0
		TASK_HUMAN_SOUND_SEARCHING     0
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_IDLE_ANGRY
		TASK_TURN_RIGHT                179
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_IDLE_ANGRY
		TASK_GET_PATH_TO_LASTPOSITION  0
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_CLEAR_LASTPOSITION        0
	Interrupts
		COND_NEW_ENEMY
		COND_CAN_RANGE_ATTACK1
		COND_CAN_RANGE_ATTACK2
		COND_CAN_MELEE_ATTACK1
		COND_CAN_MELEE_ATTACK2
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_IDLE_STAND
	Tasks
		TASK_STOP_MOVING               0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_SOUND_IDLE                0
		TASK_HUMAN_IDEALYAW            0
		TASK_FACE_IDEAL                0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE // stop possible turn animation
		TASK_HUMAN_EYECONTACT          0
		TASK_WAIT                      5
		TASK_WAIT_PVS                  0
	Interrupts
		COND_NEW_ENEMY
		COND_SEE_FEAR
		COND_SEE_HATE
		COND_SEE_DISLIKE
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_PLAYER_PUSHING
		COND_GIVE_WAY
		COND_PROVOKED
		COND_HEAR_WORLD
		COND_HEAR_COMBAT
		COND_HEAR_BULLET_IMPACT
		COND_HEAR_DANGER
		COND_HEAR_PLAYER
		COND_SMELL
		COND_IDLE_INTERRUPT
		COND_BETTER_WEAPON_AVAILABLE
//		COND_NO_PRIMARY_AMMO
//		COND_LOW_PRIMARY_AMMO

Schedule
	SCHED_HUMAN_IDLE_RESPONSE
	Tasks
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_WAIT                      7.5
		TASK_HUMAN_EYECONTACT          0
		TASK_HUMAN_SOUND_RESPOND       0
		TASK_HUMAN_IDEALYAW            0
		TASK_FACE_IDEAL                0
		TASK_HUMAN_EYECONTACT          0
	Interrupts
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_WAIT_HEAL
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_UNCROUCH            0
		TASK_FACE_TARGET               0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_WAIT                      3
//		TASK_HUMAN_EYECONTACT          0
//		TASK_HUMAN_SOUND_HEALED        0
//		TASK_HUMAN_IDEALYAW            0
//		TASK_FACE_IDEAL                0
//		TASK_HUMAN_EYECONTACT          0
	Interrupts
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER

Schedule
	SCHED_HUMAN_FACE_TARGET
	Tasks
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_FACE_TARGET               0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_TARGET_CHASE
	Interrupts
		COND_PLAYER_PUSHING
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_PROVOKED

Schedule
	SCHED_HUMAN_EXPLOSION_DIE
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_SOUND_EXPL          0
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_EXPLOSION_HIT
		TASK_HUMAN_EXPLOSION_FLY       0
		TASK_HUMAN_EXPLOSION_LAND      0
	Interrupts

Schedule
	SCHED_HUMAN_PRIMARY_MELEE_ATTACK1
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_UNCROUCH            0
		TASK_FACE_ENEMY                0
		TASK_MELEE_ATTACK1             0
	Interrupts

Schedule
	SCHED_HUMAN_POPUP_ATTACK
	Tasks
		TASK_STOP_MOVING               0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_UNCROUCH            0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_HUMAN_SOUND_CHARGE        0.3
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_FACE_ENEMY                0
		TASK_HUMAN_CHECK_FIRE          0
		TASK_RANGE_ATTACK1             0
		TASK_HUMAN_CROUCH              0
		TASK_WAIT                      0.5
	Interrupts
		COND_NEW_ENEMY
		COND_ENEMY_DEAD
		COND_HEAVY_DAMAGE
		COND_ENEMY_OCCLUDED
		COND_HEAR_DANGER
		COND_NO_PRIMARY_AMMO

Schedule
	SCHED_HUMAN_REPEL
	Tasks
		TASK_STOP_MOVING               0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_GLIDE
		TASK_FACE_IDEAL                0
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_GLIDE
	Interrupts
		COND_SEE_ENEMY
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_HEAR_COMBAT
		COND_HEAR_PLAYER

Schedule
	SCHED_HUMAN_REPEL_ATTACK
	Tasks
		TASK_STOP_MOVING               0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_GLIDE
		TASK_FACE_ENEMY                0
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_FLY
	Interrupts
		COND_ENEMY_OCCLUDED

Schedule
	SCHED_HUMAN_REPEL_LAND
	Tasks
		TASK_STOP_MOVING               0
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_LAND
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_GET_PATH_TO_LASTPOSITION  0
		TASK_RUN_PATH                  0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_CLEAR_LASTPOSITION        0
		TASK_STOP_MOVING               0
	Interrupts
		COND_SEE_ENEMY
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_HEAR_COMBAT
		COND_HEAR_PLAYER

Schedule
	SCHED_HUMAN_REPEL_LAND_SEARCH
	Tasks
		TASK_STOP_MOVING               0
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_LAND
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_IDLE_ANGRY
		TASK_TURN_RIGHT                179
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_IDLE_ANGRY
		TASK_TURN_RIGHT                179
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_HUMAN_SIGNAL_SEARCH_AND_DESTROY
	Interrupts
		COND_SEE_ENEMY
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_HEAR_PLAYER

Schedule
	SCHED_HUMAN_FAIL
	Tasks
		TASK_SET_FAIL_SCHEDULE         SCHEDULE:SCHED_FAIL_NOSTOP
		TASK_STOP_MOVING               0
		TASK_SET_ACTIVITY              ACTIVITY:ACT_IDLE
		TASK_WAIT                      1
		TASK_WAIT_PVS                  0
	Interrupts
		COND_CAN_RANGE_ATTACK1
		COND_CAN_RANGE_ATTACK2
		COND_CAN_MELEE_ATTACK1
		COND_CAN_MELEE_ATTACK2
		COND_GIVE_WAY

Schedule
	SCHED_HUMAN_BARNACLE_HIT
	Tasks
		TASK_STOP_MOVING			0
		TASK_PLAY_SEQUENCE			ACTIVITY:ACT_BARNACLE_HIT
		TASK_SET_SCHEDULE			SCHEDULE:SCHED_HUMAN_BARNACLE_PULL
	Interrupts

Schedule
	SCHED_HUMAN_BARNACLE_PULL
	Tasks
		TASK_PLAY_SEQUENCE			ACTIVITY:ACT_BARNACLE_PULL
	Interrupts

Schedule
	SCHED_HUMAN_BARNACLE_CHOMP
	Tasks
		TASK_PLAY_SEQUENCE			ACTIVITY:ACT_BARNACLE_CHOMP
		TASK_SET_SCHEDULE			SCHEDULE:SCHED_HUMAN_BARNACLE_CHEW
	Interrupts

Schedule
	SCHED_HUMAN_BARNACLE_CHEW
	Tasks
		TASK_PLAY_SEQUENCE			ACTIVITY:ACT_BARNACLE_CHEW
	Interrupts

Schedule
	SCHED_HUMAN_BARNACLE_RELEASED_HIGH
	Tasks
		TASK_HUMAN_SOUND_EXPL		0
		TASK_PLAY_SEQUENCE			ACTIVITY:ACT_BARNACLE_RELEASED
		TASK_FALL_TO_GROUND			0
		TASK_PLAY_SEQUENCE			ACTIVITY:ACT_BARNACLE_HIT_GROUND
		TASK_SUGGEST_STATE			STATE:IDLE
	Interrupts

Schedule
	SCHED_HUMAN_BARNACLE_RELEASED_LOW
	Tasks
		TASK_PLAY_SEQUENCE			ACTIVITY:ACT_IDLE
		TASK_FALL_TO_GROUND			0
		TASK_SUGGEST_STATE			STATE:IDLE
	Interrupts

// Just like SCHED_RUN_RANDOM but this distance is not hard-coded
Schedule
	SCHED_HUMAN_GRENADE_INTERACTION
	Tasks
//		TASK_SET_TOLERANCE_DISTANCE		48
		TASK_SET_ROUTE_SEARCH_TIME		1	// Spend 1 seconds trying to build a path if stuck
		TASK_HUMAN_GET_PATH_TO_RANDOM_NODE 500
		TASK_RUN_PATH					0
		TASK_WAIT_FOR_MOVEMENT			0
	Interrupts

// from alyx_episodic
Schedule
	SCHED_HUMAN_ALERT_REACT_TO_COMBAT_SOUND
	Tasks
		TASK_REACT_TO_COMBAT_SOUND		0
		TASK_SET_SCHEDULE				SCHEDULE:SCHED_ALERT_FACE_BESTSOUND
	Interrupts
		COND_NEW_ENEMY

