Schedule
	SCHED_PEASANT_STARTLE
	Tasks
		TASK_STOP_MOVING					0
		TASK_PEASANT_SOUND_STARTLE			0
		TASK_PLAY_SEQUENCE_FACE_ENEMY		ACTIVITY:ACT_FEAR_DISPLAY
		TASK_SET_ACTIVITY					ACTIVITY:ACT_IDLE
		TASK_WAIT							2.0
		TASK_WAIT_RANDOM					1.0
	Interrupts
		COND_NEW_ENEMY
		COND_SEE_ENEMY
		COND_HEAR_DANGER
		COND_HEAR_MOVE_AWAY
		COND_PLAYER_PUSHING
		COND_GIVE_WAY

Schedule
	SCHED_PEASANT_PANIC
	Tasks
		TASK_STOP_MOVING					0
		TASK_FACE_ENEMY						0
		TASK_PEASANT_SOUND_SCREAM			0.3
		TASK_PLAY_SEQUENCE_FACE_ENEMY		ACTIVITY:ACT_EXCITED
		TASK_SET_ACTIVITY					ACTIVITY:ACT_IDLE
	Interrupts
		COND_HEAR_MOVE_AWAY
		COND_PLAYER_PUSHING
		COND_GIVE_WAY

Schedule
	SCHED_PEASANT_COWER
	Tasks
		TASK_STOP_MOVING					0
		TASK_PEASANT_SOUND_FEAR				0.3
		TASK_SET_ACTIVITY					ACTIVITY:ACT_CROUCHIDLE
		TASK_WAIT							2.0
		TASK_WAIT_RANDOM					10.0
	Interrupts
		COND_NEW_ENEMY
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_ENEMY_TOO_CLOSE
		COND_HEAR_MOVE_AWAY
		COND_PLAYER_PUSHING
		COND_GIVE_WAY

