Schedule
	SCHED_CHARLIE_VICTORY_DANCE
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_UNCROUCH            0
		TASK_HUMAN_SOUND_VICTORY       0
		TASK_GET_PATH_TO_ENEMY_CORPSE  0
		TASK_WALK_PATH                 0
		TASK_WAIT_FOR_MOVEMENT         0
		TASK_STOP_MOVING               0
		TASK_FACE_ENEMY                0
		TASK_PLAY_SEQUENCE             ACTIVITY:ACT_VICTORY_DANCE
	Interrupts
		COND_NEW_ENEMY
		COND_SEE_FEAR
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_PROVOKED

