Schedule
	SCHED_HUMAN_MEDIC_HEAL
	Tasks
		TASK_HUMAN_MEDIC_CHECK_TARGET  0
		TASK_HUMAN_UNCROUCH            0
		TASK_HUMAN_MEDIC_SOUND_HEAL    0
		TASK_PLAY_SEQUENCE_FACE_TARGET ACTIVITY:ACT_HMEDIC_HEAL
		TASK_SET_ACTIVITY              ACT_IDLE
	Interrupts

Schedule
	SCHED_HUMAN_MEDIC_CHASE
	Tasks
		TASK_GET_PATH_TO_TARGET        0
		TASK_MOVE_TO_TARGET_RANGE      50
		TASK_STOP_MOVING               0
		TASK_FACE_IDEAL                0
		TASK_SET_SCHEDULE              SCHEDULE:SCHED_HUMAN_MEDIC_HEAL
	Interrupts
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_SEE_ENEMY
		COND_HEAR_DANGER
		COND_PROVOKED

