Schedule
	SCHED_MIKEFORCE_VICTORY_DANCE
	Tasks
		TASK_STOP_MOVING               0
		TASK_HUMAN_UNCROUCH            0
		TASK_WAIT_FOR_SPEAK_FINISH     0
		TASK_MIKEFORCE_VICTORY         0
		TASK_HUMAN_SOUND_VICTORY       0
		TASK_SUGGEST_STATE             STATE:IDLE
	Interrupts
		COND_NEW_ENEMY
		COND_SEE_FEAR
		COND_LIGHT_DAMAGE
		COND_HEAVY_DAMAGE
		COND_HEAR_DANGER
		COND_PROVOKED

