$modelname "palmgibs.mdl"
$cdmaterials "models\palm\palmgibs"
$cliptotextures

$scale 1.0

// 0 attachments

// 0 bone controllers

// 1 hit boxes
$hbox 0 "joint1" -16 -16 -6  16 16 6

$bodygroup studio
{
studio "ref_leaf1.smd"
studio "ref_leaf2.smd"
studio "ref_leaf3.smd"
studio "ref_leaf4.smd"
studio "ref_trunk1.smd"
studio "ref_trunk2.smd"
studio "ref_trunk3.smd"
}

// 1 sequences
$sequence idle1 "idle1" loop fps 13 

