// Created by Crowbar 0.74

// Stored modelname (without quotes): "E:\Medal Of Honour Allied Assault\main\models\static\furniture\c"
$modelname "shkaf.mdl"
$cd "."
$scale 1.0

$bodygroup "body"
{
	studio "reference"
}

$cdmaterials "models\shkaf\"


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box01" -32.91 -28.15 -0.01 29.73 0.03 87.349998

$sequence "seq-name" {
	"shkaf_anims\seq-name"
	ACT_IDLE 1
	fps 1
	loop
}
