// The original mod had shotgunshell2 with nicer texturing.
// There was also 1elephantshell.bmp but no elephantshell.smd using that texture.

$modelname "870\elephantshell2\elephantshell.mdl"
$cdmaterials "models\870\shotgunshell2"
$cliptotextures

$scale 0.5

// 0 attachments

// 0 bone controllers

// HOE:S -- reversed the facing direction in the .smd
$bodygroup studio
{
studio "elephantshell.smd"
}

// 1 sequences
$sequence idle "idle" fps 15 

