$modelname "spx_mature\acidspit\acidspit.mdl"
$cdmaterials "models\spx_mature\acidspit"
$cliptotextures

$scale 1
$staticprop

// 0 attachments

// 0 bone controllers

// 2 hit boxes
//$hbox 0 "Bone04" -1.100000 -3.460000 -2.510000  7.333769 3.170000 4.120000
//$hbox 0 "Bone04" 2.880000 -2.870000 -1.820000  8.430000 2.380000 3.420000

$bodygroup studio
{
studio "spit.smd"
}

// 1 sequences
$sequence idle "idle" loop fps 30 ACT_IDLE 1

