$modelname "bush.mdl"
$cdmaterials "models\bush"
$cliptotextures

$scale 1.0
$staticprop
//$surfaceprop "popcan"

// 0 attachments

// 0 bone controllers

// 1 hit boxes
//$hbox 0 "Box01" -16.950001 -5.760000 -0.430000  10.070000 12.770000 14.180000

$bodygroup studio
{
studio "bush.smd"
}

//$texturegroup skinfamilies
//{
// {
//  "bush1.vmt"
// }
// {
//  "bush2.vmt"
// }
// {
//  "bush3.vmt"
// }
//}

// 1 sequences
$sequence idle "idle" fps 30 

