// Created by Crowbar 0.74

// Stored modelname (without quotes): "table_coffee-maple/table_coffee-maple.mdl"
$modelname "table.mdl"
$cd "."
$scale 1.0

$bodygroup "body"
{
	studio "table_coffee-maple"
}

$cdmaterials "models\table\"


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "table_coffee" -25.200001 -41.400002 -0.036 25.182001 41.382004 36.108002

$sequence "idle" {
	"table_anims\idle"
	fps 1
	loop
}
